type_prefix : http://www.arkivverket.no/standarder/noark5/arkivstruktur/
subject_prefix : http://sesam.io/sys1/
ObjectElements:
    arkiv: {}
    arkivdel: {}
    mappe: {}
    registrering: {}
    skjerming: 
      id: null
    kassasjon:
      id: null
    korrespondansepart:
      id: null
    arkivskaper: {}
ids:
    - systemID
    - arkivskaperID
input_dir: input
backup_dir: backup
output_dir: output
